SELECT * FROM customer;

--WHAT IS THE TOTAL REVENUE GENERATED BY MALE & FEMALE CUSTOMERS?
SELECT gender, SUM(purchase_amount_usd) AS TOTAL_REVENUE
FROM customer
GROUP BY gender;


--WHICH CUSTOMERS USED A DISCOUNT BUT SPENT MORE THAN THE AVG. PURCHASE AMOUNT? 
SELECT customer_id, purchase_amount_usd 
FROM customer 
WHERE discount_applied = 'Yes' and purchase_amount_usd >= (SELECT AVG(purchase_amount_usd) FROM customer);


--WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVG. REVIEW RATING?
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating),2) as "Average_Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;


--COMPARE THE AVERAGE PURCHASE AMOUNT BETWEEN STANDARD & EXPRESS SHIPPING. 
SELECT shipping_type, 
ROUND(AVG(CAST(purchase_amount_usd AS DECIMAL(10,2))),2) AS Total_amount
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

--DO SUBSCRIBED CUSTOMERS SPEND MORE? COMPARE AVG. SPEND & TOTAL REVENUE BETWEEN SUBSCRIBERS & NON-SUBSCRIBERS.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(CAST(purchase_amount_usd AS DECIMAL(10,2))),2) AS avg_spend,
       ROUND(SUM(CAST(purchase_amount_usd AS DECIMAL(10,2))),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--WHICH 5 PRODUCTS HAVE THE HIGHEST % OF PURCHASES WITH DISCOUNTS APPLIED?
SELECT TOP 5 item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;



--SEGMENT CUSTOMERS INTO NEW, RETURNING, & LOYAL BASED ON THEIR TOTAL NO. OF PREVIOUS PURCHASES, & SHOW COUNT RESPECTIVELY. 
WITH customer_type AS 
(
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'NEW'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
    ELSE 'LOYAL'
    END AS customer_segment
FROM customer )

SELECT customer_segment,COUNT(*) AS "No_Of_Customers" 
FROM customer_type 
GROUP BY customer_segment;

--WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--ARE CUSTOMERS WHO ARE REPEAT BUYERS (MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP? 
SELECT age_group,
SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
